[package]
name = "csvtutor"
version = "0.1.0"
authors = ["Hideaki Igarashi <hide+github@5stm.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.0.0-beta.5"
serde = "1"
serde_derive = "1"
